version: '3.8'

services:
  api-gateway:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
    image: constmalytin/api-gateway:latest
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge