apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: go-messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4.12
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: NEO4J_AUTH
        - name: NEO4J_dbms_env_vars__ignore
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: neo4j-data
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc