apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
  namespace: go-messenger
type: Opaque
data:
  NEO4J_USER: bmVvNGo=               # base64 от 'neo4j'
  NEO4J_PASSWORD: eW91cl9uZW9fanBhc3N3b3JkX2hlcmU=  # base64 от 'your_neo4j_password_here'
  NEO4J_AUTH: bmVvNGoveW91cl9uZW9fanBhc3N3b3JkX2hlcmU=  # base64 от 'neo4j/your_neo4j_password_here'