apiVersion: v1
kind: Service
metadata:
  name: friendship-service
  namespace: go-messenger
spec:
  selector:
    app: friendship-service
    version: blue  # начальная версия
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003