apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: go-messenger
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: constmalytin/messaging-service-cassandra:latest
          ports:
            - containerPort: 9042
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          emptyDir: {}