apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: go-messenger
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name: cql
  selector:
    app: cassandra