apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: go-messenger
  labels:
    app: messaging-service
spec:
  selector:
    app: messaging-service
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054