// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOauthAccount = "oauth_accounts"

// OauthAccount mapped from table <oauth_accounts>
type OauthAccount struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         string    `gorm:"column:user_id;not null" json:"user_id"`
	Provider       string    `gorm:"column:provider;not null" json:"provider"`
	ProviderUserID string    `gorm:"column:provider_user_id;not null" json:"provider_user_id"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName OauthAccount's table name
func (*OauthAccount) TableName() string {
	return TableNameOauthAccount
}
