// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResetPasswordToken = "reset_password_tokens"

// ResetPasswordToken mapped from table <reset_password_tokens>
type ResetPasswordToken struct {
	Token     string    `gorm:"column:token;primaryKey;default:gen_random_uuid()" json:"token"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	ExpiresAt time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName ResetPasswordToken's table name
func (*ResetPasswordToken) TableName() string {
	return TableNameResetPasswordToken
}
