apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  namespace: go-messenger
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/cassandra