apiVersion: v1
kind: PersistentVolume
metadata:
  name: notification-cassandra-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/notification-cassandra