apiVersion: v1
kind: Service
metadata:
  name: notification-cassandra
  namespace: go-messenger
  labels:
    app: notification-cassandra
spec:
  selector:
    app: notification-cassandra
  ports:
    - port: 9242
      targetPort: 9042
      protocol: TCP
      name: cql