apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-cassandra
  namespace: go-messenger
  labels:
    app: notification-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-cassandra
  template:
    metadata:
      labels:
        app: notification-cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.0
          ports:
            - containerPort: 9242
              name: cql
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          env:
            - name: MAX_HEAP_SIZE
              value: "2G"
            - name: HEAP_NEWSIZE
              value: "400M"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JVM_OPTS
              value: >
                -Dcassandra.rpc_port=9242
                -Dcassandra.native_transport_port=9242
                -Dcassandra.storage_port=7001
                -Dcassandra.jmx.local.port=7199
                -Dcassandra.listen_address=$(POD_IP)
                -Dcassandra.broadcast_address=$(POD_IP)
                -Dcassandra.rpc_address=0.0.0.0
                -Dcassandra.broadcast_rpc_address=$(POD_IP)
                -XX:+UseG1GC
                -XX:G1HeapRegionSize=16M
                -XX:+ParallelRefProcEnabled
                -XX:MaxGCPauseMillis=200
                -XX:InitiatingHeapOccupancyPercent=45
                -XX:+HeapDumpOnOutOfMemoryError
                -Djava.net.preferIPv4Stack=true
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.cql
              subPath: init.cql
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "until cqlsh -e 'describe keyspaces' -p 9242; do sleep 5; done; cqlsh -f /docker-entrypoint-initdb.d/init.cql -p 9242"]
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: notification-cassandra-pv-claim
        - name: init-script
          configMap:
            name: cassandra-init-script