apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-blue
  namespace: go-messenger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
      version: blue
  template:
    metadata:
      labels:
        app: notification-service
        version: blue
    spec:
      containers:
      - name: notification-service
        image: constmalytin/notification-service:${VERSION}
        ports:
        - containerPort: 50055
        - containerPort: 3005
        env:
        - name: GRPC_PORT
          value: "50055"
        - name: HTTP_PORT
          value: "3005"
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: CASSANDRA_HOST
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: CASSANDRA_HOST
        - name: CASSANDRA_PORT
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: CASSANDRA_PORT
        - name: CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: CASSANDRA_KEYSPACE
        # - name: CASSANDRA_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: notification-cassandra-secret
        #       key: username
        # - name: CASSANDRA_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: notification-cassandra-secret
        #       key: password
        imagePullPolicy: Always