apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: go-messenger
spec:
  selector:
    app: notification-service
    version: blue  # начальная версия
  ports:
    - name: grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005