FROM cassandra:4.0

COPY init.cql /init.cql

CMD ["bash", "-c", "\
    docker-entrypoint.sh cassandra -f & \
    cassandra_pid=$! ; \
    until cqlsh -e 'describe keyspaces'; do \
        echo 'Ожидание запуска Cassandra...'; \
        sleep 5; \
    done; \
    cqlsh -f /init.cql; \
    wait $cassandra_pid"]