apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
  namespace: go-messenger
  labels:
    app: user-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: blue
  template:
    metadata:
      labels:
        app: user-service
        version: blue
    spec:
      containers:
      - name: user-service
        image: constmalytin/user-service:${VERSION}
        ports:
        - containerPort: 50052
        - containerPort: 3002
        env:
        - name: GRPC_PORT
          value: "50052"
        - name: HTTP_PORT
          value: "3002"
        - name: SCYLLA_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SCYLLA_HOST
        - name: SCYLLA_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SCYLLA_PORT
        - name: SCYLLA_USER
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SCYLLA_USER
        - name: SCYLLA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SCYLLA_PASSWORD
        imagePullPolicy: Always