apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: go-messenger
spec:
  selector:
    app: user-service
    version: blue  # начальная версия
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002