apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-env-file
  namespace: go-messenger
data:
  HTTP_PORT: "3000"
  AUTH_SERVICE_GRPC_PORT: "50051"
  AUTH_SERVICE_HTTP_PORT: "3001"
  USER_SERVICE_GRPC_PORT: "50052"
  USER_SERVICE_HTTP_PORT: "3002"
  FRIENDSHIP_SERVICE_GRPC_PORT: "50053"
  FRIENDSHIP_SERVICE_HTTP_PORT: "3003"
  MESSAGING_SERVICE_GRPC_PORT: "50054"
  MESSAGING_SERVICE_HTTP_PORT: "3004"
  NOTIFICATION_SERVICE_GRPC_PORT: "50055"
  NOTIFICATION_SERVICE_HTTP_PORT: "3005"
