apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-env-secret
  namespace: go-messenger
type: Opaque
stringData:
  .env: |
    PORT=3000
    AUTH_SERVICE_URL=auth-service:50051
    KAFKA_BOOTSTRAP_SERVERS=kafka:9092