apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: go-messenger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: constmalytin/auth-service:latest
        ports:
        - containerPort: 50051
        - containerPort: 3001
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: HTTP_PORT
          value: "3001"
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "auth_db"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secrets
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secrets
              key: password
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: KAFKA_BOOTSTRAP_SERVERS