apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: go-messenger
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432