apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: go-messenger
spec:
  selector:
    app: auth-service
    version: blue  # начальная версия
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001